### ISSUE TITLE
pas de reponce

### ISSUE THREAD

**Issue by Adam-sy** [nidea1/Central-Market-Discord-Bot#2]
bonjour j'ai un problème je n'ai pas de raiponce du bot sur discord peut être j'ai oublier quelque chose ?
![Capture d'écran 2023-11-20 210834](https://github.com/nidea1/Central-Market-Discord-Bot/assets/78050966/467a9855-174e-404a-b637-20330b6ba333)
merci par avance

**Comment by nidea1** [comment]
Everything seems correct, maybe you could explain your problem a little more clearly?

**Comment by Adam-sy** [comment]
when I send the command on discord example -help it does not respond the bot and online but no reaction

**Comment by nidea1** [comment]
Can I see ur terminal and .env file?

**Comment by nidea1** [comment]
> when I send the command on discord example -help it does not respond the bot and online but no reaction 

Can I see ur terminal output and .env file?

**Comment by Adam-sy** [comment]
token="xxxxxxx"

**Comment by Adam-sy** [comment]
![Capture d'écran 2023-11-21 162130](https://github.com/nidea1/Central-Market-Discord-Bot/assets/78050966/cb00dbcc-59f1-45a5-b957-b0c208d6bac8)

**Comment by Adam-sy** [comment]
![Capture d'écran 2023-11-21 162252](https://github.com/nidea1/Central-Market-Discord-Bot/assets/78050966/1c395e8c-a9e6-44e3-9835-c6aedbd2875d)

**Comment by nidea1** [comment]
> ![Capture d'écran 2023-11-21 162252](https://github.com/nidea1/Central-Market-Discord-Bot/assets/78050966/1c395e8c-a9e6-44e3-9835-c6aedbd2875d)
> 
> 

Ok everything seems good. Last question is your channel name "central-market"?

**Comment by Adam-sy** [comment]
What does this mean, I do not understand

**Comment by nidea1** [comment]
> ok thank you

You are welcome. you can edit restricted channels in bot.py line 41.
